operator couchbase-enterprise-certified (2.3.0)
k8s-operatorhub/community-operators pull request #1120
Opened 2022-04-25 17:19 UTC by tahmmee

2022-04-26 06:44 UTC, mvalarh requested changes

2022-04-26 06:44 UTC, mvalarh commented on operators/couchbase-enterprise/2.3.0/metadata/annotations.yaml
> +  operators.operatorframework.io.test.config.v1: tests/scorecard/
@tahmmee Since there are no tests in this bundle. Please remove these 2 lines

2022-04-27 22:52 UTC, mvalarh commented
@tahmmee please make image available for public
```
$ podman pull registry.connect.redhat.com/couchbase/operator:2.3.0-1
Trying to pull registry.connect.redhat.com/couchbase/operator:2.3.0-1...
Error: initializing source docker://registry.connect.redhat.com/couchbase/operator:2.3.0-1: unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
```

2022-04-28 19:08 UTC, tahmmee commented
Hi @mvalarh any insight to why upgrade is failing here?  going from 2.1.0 -> 2.3.0 does require replacement of CRD's, but not sure if that's happening.

2022-04-29 07:31 UTC, J0zi commented
retesting

2022-04-29 07:43 UTC, framework-automation commented
/merge possible

2022-04-29 07:45 UTC, framework-automation commented
/merge possible

2022-04-29 07:45 UTC, merged