keycloak-operator: Replace dead documentation link
k8s-operatorhub/community-operators pull request #3327
Opened 2023-10-06 07:44 UTC by pierreprinetti

Before this patch, clicking on the documentation link resulted in a 404 Not Found on Github pages.

With this change, the documentation link points to the "Operator" anchor in the Keycloak docs index. Note that the operator docs don't seem to be versioned on the Keycloak website.

This patch is the result of:

```sh
find . -name '*keycloak-operator*.yaml' -exec sed -i 's|\(\s\+url: \)https://www.keycloak.org/docs/latest/server_installation/index.html#_operator\s*$|\1https://www.keycloak.org/guides#operator|' {} \;
```

2023-10-06 07:45 UTC, pierreprinetti commented
/cc vmuzikar

2023-10-06 07:47 UTC, pierreprinetti commented
cc @vmuzikar

2023-10-06 07:55 UTC, vmuzikar requested changes
@pierreprinetti Thanks for the fix! Could you please rather update the [source](https://github.com/keycloak/keycloak/blob/058d00fea849a7c9ffdfa7d35aed4d324579199d/operator/src/main/java/org/keycloak/operator/controllers/KeycloakSharedCsvMetadata.java#L44) that is used for generating the CSV? We won't be fixing this retrospectively.

2023-10-06 09:37 UTC, pierreprinetti commented
@vmuzikar Here it is: https://github.com/keycloak/keycloak/pull/23777

As for the backports, I would argue that users of the previous versions may appreciate a working docs link :shrug: 
However, that's your call of course.

Have a nice day!

2023-10-19 09:27 UTC, pierreprinetti commented
I noticed that many Italians have the same exact representation of that specific frame of Conway's Game of Life's spaceship as their avatar here on Github. Would you know why, @mporrato?

2023-10-19 09:47 UTC, mporrato commented
> I noticed that many Italians have the same exact representation of that specific frame of Conway's Game of Life's glider spaceship as their avatar here on Github. Would you know why, @mporrato?

@pierreprinetti LOL, I haven't noticed the pattern you mention with fellow Italian github users, tbh, but being the "de facto" hacker symbol it's very common in general in this kind of communities. Perhaps we are all very unimaginative :shrug:

2023-10-19 09:55 UTC, framework-automation commented
/merge possible

2023-10-19 09:55 UTC, framework-automation commented
/merge possible

2023-10-19 10:01 UTC, mporrato commented
@vmuzikar do you want this merged?

2023-10-19 10:08 UTC, vmuzikar commented
@mporrato Please don't merge. We'll address this via https://github.com/keycloak/keycloak/pull/23777

2023-10-19 10:09 UTC, mporrato commented
@vmuzikar thanks. Closing.

2023-10-19 10:09 UTC, closed without merging