operator cluster-aas-operator (0.1.5)
k8s-operatorhub/community-operators pull request #4467
Opened 2024-06-06 20:22 UTC by amisstea

Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [ ] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ ] Have you tested an update to your Operator when deployed via OLM?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [ ] Modify more than one operator
* [ ] Modify an Operator you don't own
* [ ] Rename an operator - please remove and add with a different name instead
* [ ] Modify any files outside the above mentioned folders
* [ ] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [ ] Description about the managed Application and where to find more information
2. [ ] Features and capabilities of your Operator and how to use it
3. [ ] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [ ] Human readable name and 1-liner description about your Operator
* [ ] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [ ] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [ ] Links to the maintainer, source code and documentation
* [ ] Example templates for all Custom Resource Definitions intended to be used
* [ ] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

2024-06-06 20:22 UTC, amisstea commented
Attn @rawagner

2024-06-07 07:42 UTC, rawagner commented
/retest

2024-06-07 08:21 UTC, rawagner commented
/ok-to-test

2024-06-07 15:52 UTC, amisstea commented
@rawagner do you have any clues as to what might be causing the CI failures? I see the controller manager pod is stuck on creation but otherwise I can't tell what the root cause is.

```
NAME                                                              READY   STATUS              RESTARTS   AGE
032a87f20f524f2ae801033aec7b419a1e79e44f8a5d7dceb818fc99ffgvmsk   0/1     Completed           0          14m
4858040cc62e08946163366ac7a2b19fd92030ef61522d70256b218b0fdjdsl   0/1     Completed           0          14m
argocd-operator-controller-manager-b6898f485-vxl4g                1/1     Running             0          14m
cluster-aas-operator-controller-manager-6fd44c4849-5vdf8          0/2     ContainerCreating   0          14m
test-operators-ocs-9q24j                                          1/1     Running             0          15m
test-operators-ocs-prod-9zl4w                                     1/1     Running             0          15m
```

I can pull the image I used (`quay.io/stolostron/cluster-templates-operator:2.11.0-0c3131154065397d37e3b66ae635d7ea88650bf9`) without issue.

2024-06-10 06:29 UTC, rawagner commented
@amisstea Im not sure. Can you force-push to trigger the tests again ?

2024-06-19 12:03 UTC, rawagner requested changes

2024-06-19 12:05 UTC, rawagner commented on operators/cluster-aas-operator/0.1.5/manifests/cluster-aas-operator.clusterserviceversion.yaml
> +                - --tls-private-key-file=/etc/certs/tls/tls.key
this needs to be removed too

2024-06-20 03:14 UTC, amisstea commented on operators/cluster-aas-operator/0.1.5/manifests/cluster-aas-operator.clusterserviceversion.yaml
> +                  secretName: cluster-aas-operator-certs
That did the trick. Thanks!

2024-06-20 03:14 UTC, framework-automation commented
/merge possible

2024-06-20 03:14 UTC, framework-automation commented
/merge possible

2024-06-21 15:17 UTC, amisstea commented
@rawagner please merge this when you get a chance.

2024-06-21 15:24 UTC, rawagner approved these changes

2024-06-21 15:36 UTC, rawagner commented
/hold

2024-06-21 15:36 UTC, rawagner commented
/hold cancel

2024-06-21 15:45 UTC, framework-automation commented
/merge possible

2024-06-21 15:45 UTC, framework-automation commented
/merge possible

2024-06-21 15:46 UTC, merged