operator datadog-operator (1.11.1)
k8s-operatorhub/community-operators pull request #5490
Opened 2024-12-31 15:04 UTC by robot-metascanner-containerintegrations

Update operator datadog-operator (1.11.1).<br><br>Pull request triggered by timothee.bavelier@datadoghq.com.

2024-12-31 15:22 UTC, framework-automation commented
/merge possible

2024-12-31 15:22 UTC, framework-automation commented
/merge possible

2024-12-31 15:43 UTC, fanny-jiang approved these changes

2024-12-31 15:47 UTC, fanny-jiang requested changes
Let's update the ci.yml to add new team members

2024-12-31 16:04 UTC, khewonc approved these changes

2024-12-31 16:12 UTC, fanny-jiang approved these changes

2025-01-02 08:30 UTC, framework-automation commented
/merge possible

2025-01-02 08:50 UTC, framework-automation commented
/merge possible

2025-01-02 08:50 UTC, framework-automation commented
/merge possible

2025-01-02 08:50 UTC, merged